# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11SDgOFowdj_h1Eq2dPuwO3K2PkYvIGp-
"""

import requests
import json
from bs4 import BeautifulSoup
import pandas as pd
import time
from google.colab import files

import http.client
headers = { 'Authorization': "da00a0ad-4554-4813-ae1f-f250375b9bab" }
res = requests.get("https://api.api-sport.ru/v2/football/matches",headers={ "Authorization": "da00a0ad-4554-4813-ae1f-f250375b9bab"})

data = res.json()

data

data.keys()

data['matches']



import time, requests, pandas as pd
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

AUTH = "da00a0ad-4554-4813-ae1f-f250375b9bab"
BASE = "https://api.api-sport.ru/v2"
HEADERS = {"Authorization": AUTH}

THREADS = 8
MAX_RPM = 150
_req_count, _t0 = 0, time.time()

DATE_INPUT = "03.11.2025"
TARGET_DATE = datetime.strptime(DATE_INPUT, "%d.%m.%Y").strftime("%Y-%m-%d")

def comb():
    global _req_count, _t0
    _req_count += 1
    if _req_count >= MAX_RPM:
        elapsed = time.time() - _t0
        if elapsed < 60:
            time.sleep(60 - elapsed)
        _t0, _req_count = time.time(), 0

def _get(url, params=None, retries=3, backoff=1.5):
    for i in range(retries):
        try:
            comb()
            r = requests.get(url, headers=HEADERS, params=params, timeout=25)
            if r.status_code == 200: return r.json()
            if r.status_code in (429,500,502,503,504): time.sleep(backoff*(i+1)); continue
            r.raise_for_status()
        except Exception:
            time.sleep(backoff*(i+1))
    return {}

def get_sports():
    js = _get(f"{BASE}/sport") or {}
    key = next((k for k in ("sports","data","results","docs","items") if k in js), None)
    if not key: return ["football","ice-hockey","basketball","tennis","table-tennis","esports"]
    slugs = []
    for it in js.get(key, []):
        s = it.get("slug") or it.get("key") or it.get("code") or it.get("name")
        if isinstance(s, str): slugs.append(s)
    return sorted(set(slugs)) or ["football","ice-hockey","basketball","tennis","table-tennis","esports"]

def fetch_matches_one_page(sport, page):
    return _get(f"{BASE}/{sport}/matches", params={"page": page, "date": TARGET_DATE})

def fetch_matches_sport(sport):
    js = fetch_matches_one_page(sport, 1)
    list_key = next((k for k in ("matches","data","results","docs","items") if k in js), None)
    items = js.get(list_key, []) if list_key else []
    pager = js.get("pager") or js.get("meta") or {}
    pages = pager.get("pages") or pager.get("totalPages") or pager.get("last_page") or 1
    for p in range(2, int(pages)+1):
        more = fetch_matches_one_page(sport, p)
        lk = next((k for k in ("matches","data","results","docs","items") if k in more), None)
        items += more.get(lk, []) if lk else []
    if not items: return pd.DataFrame()
    df = pd.json_normalize(items, sep="_")
    if "id" in df.columns: df.rename(columns={"id":"match_id"}, inplace=True)
    if "matchId" in df.columns: df.rename(columns={"matchId":"match_id"}, inplace=True)
    df["sport"] = sport
    want = [
        "match_id","sport","status","dateEvent","startTimestamp",
        "tournament_id","tournament_name","category_id","category_name",
        "season_id","season_name","venue_name","venue_city_name","venue_country_name",
        "homeTeam_id","homeTeam_name","awayTeam_id","awayTeam_name",
        "homeScore_current","awayScore_current"
    ]
    have = [c for c in want if c in df.columns]
    return df[have].copy() if have else df

def main():
    sports = get_sports()
    frames = []
    with ThreadPoolExecutor(max_workers=THREADS) as ex:
        fut = {ex.submit(fetch_matches_sport, s): s for s in sports}
        for f in as_completed(fut):
            s = fut[f]
            try:
                df = f.result()
                if not df.empty: frames.append(df)
            except Exception as e:
                print(f"{s}: ошибка {e}")
    if frames:
        out = pd.concat(frames, ignore_index=True)
        out.to_csv(f"matches_{TARGET_DATE}.csv", index=False, encoding="utf-8")
        print(f"{DATE_INPUT}: всего {len(out)} строк → matches_{TARGET_DATE}.csv")
    else:
        print(f"{DATE_INPUT}: нет данных")

if __name__ == "__main__":
    main()









